Fix more warnings.
Fix sign conversion warnings.
Removing heavy unnecessary includes.

Change-Id: I992f43065498823098a875badb020c7c84fc4797

diff --git a/BuildTools/Git/Hooks/pre-commit b/BuildTools/Git/Hooks/pre-commit
--- a/BuildTools/Git/Hooks/pre-commit
+++ b/BuildTools/Git/Hooks/pre-commit
@@ -16,4 +16,8 @@ for file in $(git diff --cached --name-only); do
 		echo "ERROR: '$file' has a copyright error. Aborting commit."
 		exit -1
 	fi
+	if ! BuildTools/CheckHeaders.py $file; then
+		echo "ERROR: '$file' failed header sanity test. Aborting commit."
+		exit -1
+	fi
 done
