Restrict pre-commit copyright check to added files
Previously the pre-commit would require a correct copyright
header on all files, including modified files that only have a
couple lines changed.
Now, a correct copyright file header is only required on new files
added to the repository.

Test-Information:

Changed git author information to a new user and tried committing
a changed file, and afterwards a new file. Only the commit of a
new file failed due to missing copyright header. It was accepted
after setting BSD header.

Change-Id: I8e1324846fd904a72728e7c01da4c98f49a77282

diff --git a/BuildTools/Git/Hooks/pre-commit b/BuildTools/Git/Hooks/pre-commit
--- a/BuildTools/Git/Hooks/pre-commit
+++ b/BuildTools/Git/Hooks/pre-commit
@@ -4,16 +4,21 @@ IFS='
 '
 
 echo "Checking tabs & copyrights ..."
+for file in $(git diff --cached --diff-filter=A --name-only); do
+	if [ ! -f $file ]; then
+		continue
+	fi
+	if ! BuildTools/Copyrighter.py check-copyright $file; then
+		echo "ERROR: '$file' has a copyright error. Aborting commit."
+		exit -1
+	fi
+done
 for file in $(git diff --cached --name-only); do
 	if [ ! -f $file ]; then
 		continue
 	fi
 	if ! BuildTools/CheckTabs.py $file; then
 		echo "ERROR: '$file' contains expanded tabs. Aborting commit."
-		exit -1
-	fi
-	if ! BuildTools/Copyrighter.py check-copyright $file; then
-		echo "ERROR: '$file' has a copyright error. Aborting commit."
 		exit -1
 	fi
 	if ! BuildTools/CheckHeaders.py $file; then
