Update pre-commit hook to check copyrights.

diff --git a/BuildTools/Git/Hooks/pre-commit b/BuildTools/Git/Hooks/pre-commit
--- a/BuildTools/Git/Hooks/pre-commit
+++ b/BuildTools/Git/Hooks/pre-commit
@@ -5,3 +5,8 @@ if ! BuildTools/CheckTabs.py; then
 	echo "Expanded tabs found. Aborting commit."
 	exit -1
 fi
+
+echo "Checking copyrights ..."
+if ! BuildTools/Copyrighter.py check-all-copyrights; then
+	echo "Copyright error found. Aborting commit."
+	exit -1
